Added Notebook for Decision Trees
madewithml/guides pull request #23
Opened 2020-10-18 17:18 UTC by SauravMaheshkar

Hey, Thanks for creating this PR. Ensure you have checked the applicable boxes :smiley

## What does this PR do?

Fixes # (issue)

### Checklist

- [x] Did you read the [contributor guideline](https://github.com/madewithml/hacktoberfest/blob/main/CONTRIBUTING.md)?

- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/madewithml/hacktoberfest/pulls) for the same update/change?

### New Tutorial Submissions:

1. [x] Does your code meet the requirements?
2. [x] Have you documented the code well?

### Changes to Documetnations / Maintainence Features:

- [ ] Have you added an explanation of what your changes do and why you'd like us to include them?
- [ ] Have you written new tests for your core changes, as applicable?
- [ ] Have you successfully ran tests with your changes locally?

### Did you have fun?
Make sure you had fun coding 🙃

2020-10-19 06:54 UTC, oke-aditya commented
Oh! Here is the PR, you can ask for review from people so that we get notified 👍

2020-10-19 07:03 UTC, oke-aditya commented on projects/machine_learning/Decision Trees.ipynb
> +{
<p>You can avoid pip install in the notebook and simply let me know your requirements. I can add them to <code>txt</code>  files.</p><p> </p><p>We have binder though to run these tutorials.</p>
<br/>

 _Reply via <a href='https://app.reviewnb.com/madewithml/guides/pull/23/discussion/'>ReviewNB</a>_ <div id='ReviewNBCommentContext-DoNotDelete' style='display:none' data-state='OPEN' data-cellIndex='1'/>

2020-10-19 07:03 UTC, oke-aditya commented on projects/machine_learning/Decision Trees.ipynb
> +{
<p>There is another popular algoirthm called CART. Can we describe a bit.</p><p> </p>
<br/>

 _Reply via <a href='https://app.reviewnb.com/madewithml/guides/pull/23/discussion/'>ReviewNB</a>_ <div id='ReviewNBCommentContext-DoNotDelete' style='display:none' data-state='OPEN' data-cellIndex='13'/>

2020-10-19 07:03 UTC, oke-aditya commented on projects/machine_learning/Decision Trees.ipynb
> +{
<p>Can we avoid using <code>plotly</code> and stick with <code>matplotlib</code></p><p>  </p><p>It keeps our dependencies low and easy to maintain.</p>
<br/>

 _Reply via <a href='https://app.reviewnb.com/madewithml/guides/pull/23/discussion/'>ReviewNB</a>_ <div id='ReviewNBCommentContext-DoNotDelete' style='display:none' data-state='OPEN' data-cellIndex='18'/>

2020-10-19 07:03 UTC, oke-aditya commented on projects/machine_learning/Decision Trees.ipynb
> +{
<p>Can we explain how each of these parameters affects trees?</p>
<br/>

 _Reply via <a href='https://app.reviewnb.com/madewithml/guides/pull/23/discussion/'>ReviewNB</a>_ <div id='ReviewNBCommentContext-DoNotDelete' style='display:none' data-state='OPEN' data-cellIndex='22'/>

2020-10-19 07:03 UTC, oke-aditya commented on projects/machine_learning/Decision Trees.ipynb
> +{
<p>Can we shift this cell up</p>
<br/>

 _Reply via <a href='https://app.reviewnb.com/madewithml/guides/pull/23/discussion/'>ReviewNB</a>_ <div id='ReviewNBCommentContext-DoNotDelete' style='display:none' data-state='OPEN' data-cellIndex='23'/>

2020-10-19 07:03 UTC, oke-aditya commented on projects/machine_learning/Decision Trees.ipynb
> +{
<p>I suggest to stick with <code>iris</code>  dataset and show different visualizations of trees. </p><p> </p><p>We can visualize for a few important parameters such as depth, leaf size etc.</p><p> </p><p>We can probably show a very nice guide to how a decision tree works and how to visualize it while it works.</p>
<br/>

 _Reply via <a href='https://app.reviewnb.com/madewithml/guides/pull/23/discussion/'>ReviewNB</a>_ <div id='ReviewNBCommentContext-DoNotDelete' style='display:none' data-state='OPEN' data-cellIndex='30'/>

2020-10-19 07:13 UTC, SauravMaheshkar commented on projects/machine_learning/Decision Trees.ipynb
> +{
<p>Okay. I've made a <code>requirements.txt</code>  file with the required dependencies.</p>

2020-10-19 07:15 UTC, SauravMaheshkar commented on projects/machine_learning/Decision Trees.ipynb
> +{
<p>I've added a short description of CART as well</p>

2020-10-19 07:16 UTC, SauravMaheshkar commented on projects/machine_learning/Decision Trees.ipynb
> +{
<p>Done</p>

2020-10-19 07:33 UTC, oke-aditya commented on projects/machine_learning/Decision Trees.ipynb
> +{
<p>Hi ! Thanks for the PR</p><p> </p><p>I liked the notebook. but we can have little changes to make this even better</p>

2020-10-19 07:37 UTC, SauravMaheshkar commented on projects/machine_learning/Decision Trees.ipynb
> +{
<p>Can I use <code>seaborn</code>  ??</p>

2020-10-19 08:19 UTC, oke-aditya commented on projects/machine_learning/Decision Trees.ipynb
> +{
You can avoid that file, we will added requirements at root when #21 is merged.

2020-10-19 08:19 UTC, SauravMaheshkar commented
I've updated the Notebook. 

Please tell suggestions.

2020-10-19 08:24 UTC, oke-aditya commented on projects/machine_learning/Decision Trees.ipynb
> +{
I just checked the requirements of `seaborn`. It need `numpy, pandas, matplotlib` which I feel are fine.
You can use `seaborn`.

Plotly is very nice for visualization but it has lot of dependencies. We want to keep this with minimal dependencies.

2020-10-19 08:29 UTC, oke-aditya commented on projects/machine_learning/Decision Trees/Decision Trees.ipynb
> +{
<p>We don't need to <code>import load_iris</code>  again.</p><p> </p>
<br/>

 _Reply via <a href='https://app.reviewnb.com/madewithml/guides/pull/23/discussion/'>ReviewNB</a>_ <div id='ReviewNBCommentContext-DoNotDelete' style='display:none' data-state='OPEN' data-cellIndex='42'/>

2020-10-19 08:29 UTC, oke-aditya commented on projects/machine_learning/Decision Trees/Decision Trees.ipynb
> +{
<p>Can we increase the figure size a bit?</p><p> </p>
<br/>

 _Reply via <a href='https://app.reviewnb.com/madewithml/guides/pull/23/discussion/'>ReviewNB</a>_ <div id='ReviewNBCommentContext-DoNotDelete' style='display:none' data-state='OPEN' data-cellIndex='44'/>

2020-10-19 08:29 UTC, oke-aditya commented on projects/machine_learning/Decision Trees/Decision Trees.ipynb
> +{
<p>I guess we can avoid graphviz, we had sufficient visualization and we can refer people to use graphviz.</p><p> </p><p>This will reduce graphviz dependency too.</p>
<br/>

 _Reply via <a href='https://app.reviewnb.com/madewithml/guides/pull/23/discussion/'>ReviewNB</a>_ <div id='ReviewNBCommentContext-DoNotDelete' style='display:none' data-state='OPEN' data-cellIndex='46'/>

2020-10-19 08:35 UTC, oke-aditya commented
We can include more thoery on decision trees. I leave this up to you.
Also, let me know what more you would like to include 😄 

P.S. Sometimes reviews might take time.

2020-10-20 07:25 UTC, oke-aditya requested changes
Needs minor changes 😄

2020-10-20 12:24 UTC, neomatrix369 commented
> Changes to Documetnations / Maintainence Features:

GitHub template issue ^^^ (Documetnations ==> Documentations)

2020-10-20 12:29 UTC, oke-aditya commented
> 
> 
> > Changes to Documetnations / Maintainence Features:
> 
> GitHub template issue ^^^ (Documetnations ==> Documentations)

I have fixed it in #24 . 😄 It will reflect in new PRs

2020-10-22 16:13 UTC, oke-aditya commented on projects/machine_learning/Decision Trees/Decision Trees.ipynb
> +{
<p>Again same comment from classification. Can we explain how the model works with some metrics such as <code>R2 score</code>  or <code>MSE</code>  etc.</p><p> </p><p>Also, a little more thoery on regression is fine, I leave this optional</p>

2021-04-29 02:08 UTC, closed without merging